### ISSUE TITLE
We should check APIs to handle JSON arrays correctly

### ISSUE THREAD

**Issue by riccardo** [ismb/jemma#189]
As suggested by vito during Meeting on Apr 15. http://haacked.com/archive/2008/11/20/anatomy-of-a-subtle-json-vulnerability.aspx/

**Comment by Tinwor** [comment]
According to [this question](http://stackoverflow.com/questions/2669690/why-does-google-prepend-while1-to-their-json-responses)  in the APIs server side it should be added a string (e.g. "(EhRocks)") and when the client receive the response make a substring before process the result
