### ISSUE TITLE
We should automate the creation of releases zip

### ISSUE THREAD

**Issue by riccardo** [ismb/jemma#199]
This is about the procedure we use to build distributions e.g. like we did for [jemma-bin-0.9.zip](https://github.com/ismb/jemma/releases/download/0.9/jemma-bin-0.9.zip)

The manual procedure is quite straightforward - but error-prone.

We should automate it.
(we should also use the same with the "fake devices" configuration used for testing)

**Comment by cdealti** [comment]
Hello,
  Is the manual procedure documented somewhere?

**Comment by riccardo** [comment]
It's documented [here](https://github.com/ismb/jemma/blob/master/ReleaseManual.md), but note that this is mostly "internal" guide followed when we package a new release.
